version: '3.7'

networks:
  minima_testnet:
    name: minima_testnet
  outside_minima_testnet:
    name: outside_minima_testnet

services:
  minima_one:
    image: minima:latest
    command: -daemon -genesis -automine -noconnect -test -clean -rpcenable
    networks:
      minima_testnet:
        aliases:
          - minima_one
    ports:
      #- "9001:9001"
      - "9002:9002"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  minima_peer:
    image: minima:latest
    command: -daemon -test -port 9121 -clean
    networks:
      minima_testnet:
        aliases:
          - minima_peer
    depends_on:
      - minima_one
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
  minima_client:
    image: minima:latest
    command: -test -daemon -isclient -p2pnode minima_one:9001 -clean
    networks:
      minima_testnet:
        aliases:
          - minima_client
    depends_on:
      - minima_one
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
  minima_no_p2p:
    image: minima:latest
    command: -test -daemon -nop2p -connect minima_one:9001  -clean
    networks:
      minima_testnet:
        aliases:
          - minima_client
    depends_on:
      - minima_one
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M